---
- name: ensure web proxy container is running
  become: yes
  docker:
    image: "kinoko/web-proxy"
    name: web_proxy
    volumes:
      - "{{ docker_sock_path }}:/tmp/docker.sock:rw"
    ports:
      - "{{ web_proxy_listen_ip }}:80:80"
      - "{{ web_proxy_listen_ip }}:443:443"
    state: reloaded
    pull: always
    restart_policy: always
    docker_api_version: "{{ docker_api_version }}"
