---
- name: ensure web proxy container is running
  become: yes
  docker:
    image: "kinoko/web_proxy"
    name: web_proxy
    volumes:
      - "{{ docker_sock_path }}:/tmp/docker.sock:rw"
    ports:
      - 80:80
      - 443:443
    state: reloaded
    pull: always
    restart_policy: always
    docker_api_version: "{{ docker_api_version }}"
