---
- name: ensure web proxy container is running
  become: yes
  docker_container:
    image: "kinoko/web-proxy"
    name: web_proxy
    state: started
    volumes:
      - "{{ docker_sock_path }}:/tmp/docker.sock:rw"
      - "{{ web_proxy_conf_path }}/certs:/etc/nginx/certs:rw"
      - "{{ web_proxy_conf_path }}/vhost.d:/etc/nginx/vhost.d:rw"
      - "{{ web_proxy_conf_path }}/conf.d:/etc/nginx/conf.d:rw"
      - "{{ web_proxy_conf_path }}/htpasswd:/etc/nginx/htpasswd:rw"
    ports:
      - "{{ web_proxy_listen_ip }}:80:80"
      - "{{ web_proxy_listen_ip }}:443:443"
    pull: yes
    restart_policy: always
