---
- name: ensure web proxy container is running
  become: yes
  docker_container:
    image: "kinoko/web-proxy"
    name: web_proxy
    state: started
    volumes:
      - "{{ docker_sock_path }}:/tmp/docker.sock:rw"
      - "{{ web_proxy_certs_path }}:/etc/nginx/certs:rw"
      - "{{ web_proxy_htpasswd_path }}:/etc/nginx/htpasswd:rw"
    ports:
      - "{{ web_proxy_listen_ip }}:80:80"
      - "{{ web_proxy_listen_ip }}:443:443"
    pull: yes
    restart_policy: always
